# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"*\n\nDateMovies\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x18\n\x06UserID\x12\x0e\n\x06userid\x18\x01 \x01(\t\":\n\nAddBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0e\n\x06movies\x18\x03 \x01(\t\"B\n\x0f\x42ookingResponse\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x1f\n\ndatemovies\x18\x02 \x03(\x0b\x32\x0b.DateMovies\"\x0e\n\x0c\x45mptyBooking2\xa1\x01\n\x07\x42ooking\x12\x32\n\x13GetBookingsByUserId\x12\x07.UserID\x1a\x10.BookingResponse\"\x00\x12\x32\n\x0bGetBookings\x12\r.EmptyBooking\x1a\x10.BookingResponse\"\x00\x30\x01\x12.\n\x0b\x41\x64\x64\x42ookings\x12\x0b.AddBooking\x1a\x10.BookingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATEMOVIES']._serialized_start=17
  _globals['_DATEMOVIES']._serialized_end=59
  _globals['_USERID']._serialized_start=61
  _globals['_USERID']._serialized_end=85
  _globals['_ADDBOOKING']._serialized_start=87
  _globals['_ADDBOOKING']._serialized_end=145
  _globals['_BOOKINGRESPONSE']._serialized_start=147
  _globals['_BOOKINGRESPONSE']._serialized_end=213
  _globals['_EMPTYBOOKING']._serialized_start=215
  _globals['_EMPTYBOOKING']._serialized_end=229
  _globals['_BOOKING']._serialized_start=232
  _globals['_BOOKING']._serialized_end=393
# @@protoc_insertion_point(module_scope)
